FROM python:3.11

WORKDIR /app

COPY requirements.txt azure_blog_reader.py /app/
COPY client_modules/ /app/client_modules/

RUN pip install --no-cache-dir -r requirements.txt

CMD ./azure_blog_reader.py



